from Model.IFetching import IFetching
from Model.Data import Data
from pytube import Playlist

class FetchingPlaylist(IFetching):
    def __fetchPlaylist(self,url:str):
        return Playlist(url)

    def fetchContent(self,data:Data,url:str,index=None):
        playlist = self.__fetchPlaylist(url)
        if playlist:
            data.clearVideoData()
            for video in playlist.videos :
                data.videoData.append(video)
        else:
            raise Exception("Cannot fetch the playlist. \n\nMake sure the playlist is not private or autogenerated.")
    
